# hotswap-agent.properties
# place in: src/main/resources/hotswap-agent.properties

# disable plugins that conflict with modlauncher
disabledPlugins=Proxy,Spring,Hibernate,Jersey,Jetty,Tomcat,CDI,Cglib

# point directly to compiled classes to bypass full project scanning
extraClasspath=build/classes/java/main

# auto reload settings
autoHotswap=true
autoHotswap.port=8000